$NetBSD$

--- ../librespot/playback/Cargo.toml.orig	2018-11-19 14:03:35.000000000 +0000
+++ ../librespot/playback/Cargo.toml
@@ -15,7 +15,8 @@ futures = "0.1.8"
 log = "0.3.5"
 byteorder = "1.2.1"
 
-alsa            = { git = "https://github.com/plietar/rust-alsa", optional = true }
+#alsa            = { git = "https://github.com/plietar/rust-alsa", optional = true }
+alsa            = { path = "../../rust-alsa", optional = true }
 portaudio-rs    = { version = "0.3.0", optional = true }
 libpulse-sys    = { version = "0.0.0", optional = true }
 jack            = { version = "0.5.3", optional = true }
